/**
 * Some content sourced from the NotEnoughUpdates-REPO repository
 * under the MIT License.
 */

export const enchants: Record<string, string[]> = {
  "Sword/Longsword": [
    "bane_of_arthropods",
    "cleave",
    "critical",
    "cubism",
    "dragon_hunter",
    "ender_slayer",
    "execute",
    "experience",
    "fire_aspect",
    "first_strike",
    "giant_killer",
    "impaling",
    "knockback",
    "lethality",
    "life_steal",
    "looting",
    "luck",
    "mana_steal",
    "prosecute",
    "scavenger",
    "sharpness",
    "smite",
    "syphon",
    "titan_killer",
    "thunderlord",
    "thunderbolt",
    "triple_strike",
    "vampirism",
    "venomous",
    "vicious",
    "ultimate_one_for_all",
    "ultimate_soul_eater",
    "ultimate_chimera",
    "ultimate_combo",
    "ultimate_swarm",
    "ultimate_wise",
    "smoldering",
    "ultimate_inferno",
    "ultimate_fatal_tempo",
    "tabasco",
    "champion",
    "divine_gift",
  ],
  Bow: [
    "chance",
    "cubism",
    "dragon_hunter",
    "flame",
    "impaling",
    "infinite_quiver",
    "piercing",
    "overload",
    "power",
    "punch",
    "snipe",
    "ultimate_soul_eater",
    "ultimate_swarm",
    "ultimate_wise",
    "ultimate_rend",
    "smoldering",
    "ultimate_inferno",
    "ultimate_fatal_tempo",
    "divine_gift",
    "tabasco",
    "ultimate_duplex",
    "vicious",
  ],
  Axe: [
    "efficiency",
    "replenish",
    "silk_touch",
    "turbo_cocoa",
    "turbo_melon",
    "turbo_pumpkin",
    "delicate",
    "sunder",
    "dedication",
  ],
  "Mining Tool": [
    "compact",
    "efficiency",
    "experience",
    "fortune",
    "silk_touch",
    "pristine",
    "smelting_touch",
  ],
  "Fishing Rod": [
    "angler",
    "blessing",
    "caster",
    "expertise",
    "frail",
    "looting",
    "luck_of_the_sea",
    "lure",
    "magnet",
    "spiked_hook",
    "impaling",
    "charm",
    "corruption",
    "ultimate_inferno",
    "ultimate_fatal_tempo",
    "ultimate_flash",
    "tabasco",
    "piscary",
  ],
  "Fishing Weapon": [
    "angler",
    "blessing",
    "caster",
    "expertise",
    "frail",
    "looting",
    "luck_of_the_sea",
    "lure",
    "magnet",
    "spiked_hook",
    "bane_of_arthropods",
    "cleave",
    "critical",
    "cubism",
    "dragon_hunter",
    "ender_slayer",
    "execute",
    "experience",
    "fire_aspect",
    "first_strike",
    "giant_killer",
    "impaling",
    "knockback",
    "lethality",
    "life_steal",
    "looting",
    "luck",
    "mana_steal",
    "prosecute",
    "scavenger",
    "sharpness",
    "smite",
    "syphon",
    "titan_killer",
    "thunderlord",
    "thunderbolt",
    "triple_strike",
    "vampirism",
    "venomous",
    "vicious",
    "ultimate_one_for_all",
    "ultimate_soul_eater",
    "ultimate_chimera",
    "ultimate_combo",
    "ultimate_swarm",
    "ultimate_wise",
    "smoldering",
    "ultimate_inferno",
    "ultimate_fatal_tempo",
    "ultimate_flash",
    "tabasco",
    "champion",
    "divine_gift",
    "piscary",
  ],
  Shovel: ["efficiency", "silk_touch"],
  Hoe: [
    "replenish",
    "harvesting",
    "turbo_wheat",
    "turbo_cactus",
    "turbo_cane",
    "turbo_warts",
    "turbo_carrot",
    "turbo_potato",
    "turbo_mushrooms",
    "cultivating",
    "delicate",
    "dedication",
  ],
  Helmet: [
    "big_brain",
    "blast_protection",
    "fire_protection",
    "projectile_protection",
    "protection",
    "growth",
    "rejuvenate",
    "respite",
    "aqua_affinity",
    "thorns",
    "respiration",
    "ultimate_bank",
    "ultimate_last_stand",
    "ultimate_legion",
    "ultimate_no_pain_no_gain",
    "ultimate_wisdom",
    "hardened_mana",
    "strong_mana",
    "mana_vampire",
    "ferocious_mana",
    "hecatomb",
    "ultimate_habanero_tactics",
    "ultimate_bobbin_time",
    "transylvanian",
    "pesterminator",
  ],
  Chestplate: [
    "protection",
    "blast_protection",
    "fire_protection",
    "projectile_protection",
    "growth",
    "rejuvenate",
    "respite",
    "thorns",
    "counter_strike",
    "true_protection",
    "ultimate_bank",
    "ultimate_last_stand",
    "ultimate_legion",
    "ultimate_no_pain_no_gain",
    "ultimate_wisdom",
    "hardened_mana",
    "strong_mana",
    "mana_vampire",
    "ferocious_mana",
    "ultimate_habanero_tactics",
    "ultimate_bobbin_time",
    "reflection",
    "pesterminator",
  ],
  Leggings: [
    "protection",
    "blast_protection",
    "fire_protection",
    "projectile_protection",
    "growth",
    "rejuvenate",
    "respite",
    "smarty_pants",
    "thorns",
    "ultimate_bank",
    "ultimate_last_stand",
    "ultimate_legion",
    "ultimate_no_pain_no_gain",
    "ultimate_wisdom",
    "hardened_mana",
    "strong_mana",
    "mana_vampire",
    "ferocious_mana",
    "ultimate_habanero_tactics",
    "ultimate_bobbin_time",
    "pesterminator",
  ],
  Boots: [
    "protection",
    "blast_protection",
    "fire_protection",
    "projectile_protection",
    "growth",
    "sugar_rush",
    "rejuvenate",
    "respite",
    "feather_falling",
    "depth_strider",
    "frost_walker",
    "thorns",
    "ultimate_bank",
    "ultimate_last_stand",
    "ultimate_legion",
    "ultimate_no_pain_no_gain",
    "ultimate_wisdom",
    "hardened_mana",
    "strong_mana",
    "mana_vampire",
    "ferocious_mana",
    "ultimate_habanero_tactics",
    "ultimate_bobbin_time",
    "pesterminator",
  ],
  Necklace: ["cayenne", "prosperity", "green_thumb", "quantum", "ultimate_the_one"],
  "Gloves/Belt/Bracelet/Cloak": ["cayenne", "prosperity", "green_thumb"],
};

export const maxEnchantTiers: Record<string, number> = {
  bane_of_arthropods: 7,
  cleave: 6,
  critical: 7,
  cubism: 6,
  dragon_hunter: 5,
  ender_slayer: 7,
  execute: 6,
  experience: 5,
  fire_aspect: 3,
  first_strike: 5,
  giant_killer: 7,
  impaling: 3,
  knockback: 2,
  lethality: 6,
  life_steal: 5,
  looting: 5,
  luck: 7,
  mana_steal: 3,
  prosecute: 6,
  scavenger: 5,
  sharpness: 7,
  smite: 7,
  syphon: 5,
  titan_killer: 7,
  thunderlord: 7,
  thunderbolt: 6,
  triple_strike: 5,
  vampirism: 6,
  venomous: 6,
  vicious: 5,
  ultimate_one_for_all: 1,
  ultimate_soul_eater: 5,
  ultimate_chimera: 5,
  ultimate_combo: 5,
  ultimate_swarm: 5,
  ultimate_wise: 5,
  smoldering: 5,
  ultimate_inferno: 5,
  ultimate_fatal_tempo: 5,
  tabasco: 3,
  champion: 10,
  divine_gift: 3,
  aiming: 5,
  chance: 5,
  flame: 1,
  infinite_quiver: 10,
  piercing: 1,
  overload: 5,
  power: 7,
  punch: 2,
  snipe: 4,
  ultimate_rend: 5,
  ultimate_duplex: 5,
  efficiency: 10,
  replenish: 1,
  silk_touch: 1,
  turbo_cocoa: 5,
  turbo_melon: 5,
  turbo_pumpkin: 5,
  delicate: 5,
  sunder: 6,
  dedication: 4,
  compact: 10,
  fortune: 4,
  pristine: 5,
  smelting_touch: 1,
  angler: 6,
  blessing: 6,
  caster: 6,
  expertise: 10,
  frail: 6,
  luck_of_the_sea: 6,
  lure: 6,
  magnet: 6,
  spiked_hook: 6,
  charm: 5,
  corruption: 5,
  ultimate_flash: 5,
  piscary: 6,
  harvesting: 6,
  turbo_wheat: 5,
  turbo_cactus: 5,
  turbo_cane: 5,
  turbo_warts: 5,
  turbo_carrot: 5,
  turbo_potato: 5,
  turbo_mushrooms: 5,
  cultivating: 10,
  big_brain: 5,
  blast_protection: 7,
  fire_protection: 7,
  projectile_protection: 7,
  protection: 7,
  growth: 7,
  rejuvenate: 5,
  respite: 5,
  aqua_affinity: 1,
  thorns: 3,
  respiration: 3,
  ultimate_bank: 5,
  ultimate_last_stand: 5,
  ultimate_legion: 5,
  ultimate_no_pain_no_gain: 5,
  ultimate_wisdom: 5,
  hardened_mana: 10,
  strong_mana: 10,
  mana_vampire: 10,
  ferocious_mana: 10,
  hecatomb: 10,
  ultimate_habanero_tactics: 5,
  ultimate_bobbin_time: 5,
  transylvanian: 5,
  pesterminator: 5,
  counter_strike: 5,
  true_protection: 1,
  reflection: 5,
  smarty_pants: 5,
  sugar_rush: 3,
  feather_falling: 10,
  depth_strider: 3,
  frost_walker: 2,
  cayenne: 5,
  prosperity: 5,
  green_thumb: 5,
  quantum: 5,
  ultimate_the_one: 5,
};

export const ultimateEnchantments = [
  "Chimera",
  "Combo",
  "Fatal Tempo",
  "Inferno",
  "One For All",
  "Soul Eater",
  "Swarm",
  "Ultimate Jerry",
  "Ultimate Wise",
  "Duplex",
  "Fatal Tempo",
  "Infero",
  "Rend",
  "Bank",
  "Habanero Tactics",
  "Bobbin' Time",
  "Last Stand",
  "Legion",
  "No Pain No Gain",
  "Wisdom",
  "Flash",
  "The One",
];

export const displayNames: Record<string, string> = {
  pesterminator: "Pesterminator",
  bane_of_arthropods: "Bane of Arthropods",
  champion: "Champion",
  cleave: "Cleave",
  critical: "Critical",
  cubism: "Cubism",
  divine_gift: "Divine Gift",
  dragon_hunter: "Dragon Hunter",
  ender_slayer: "Ender Slayer",
  execute: "Execute",
  experience: "Experience",
  fire_aspect: "Fire Aspect",
  first_strike: "First Strike",
  giant_killer: "Giant Killer",
  impaling: "Impaling",
  knockback: "Knockback",
  lethality: "Lethality",
  life_steal: "Life Steal",
  looting: "Looting",
  luck: "Luck",
  mana_steal: "Mana Steal",
  prosecute: "Prosecute",
  scavenger: "Scavenger",
  sharpness: "Sharpness",
  smite: "Smite",
  smoldering: "Smoldering",
  syphon: "Syphon",
  tabasco: "Tabasco",
  thunderbolt: "Thunderbolt",
  thunderlord: "Thunderlord",
  titan_killer: "Titan Killer",
  triple_strike: "Triple-Strike",
  vampirism: "Vampirism",
  venomous: "Venomous",
  vicious: "Vicious",
  ultimate_chimera: "Chimera",
  ultimate_combo: "Combo",
  ultimate_fatal_tempo: "Fatal Tempo",
  ultimate_inferno: "Inferno",
  ultimate_one_for_all: "One For All",
  ultimate_soul_eater: "Soul Eater",
  ultimate_swarm: "Swarm",
  ultimate_jerry: "Ultimate Jerry",
  ultimate_wise: "Ultimate Wise",
  chance: "Chance",
  dragon_tracer: "Dragon Tracer",
  flame: "Flame",
  infinite_quiver: "Infinite Quiver",
  overload: "Overload",
  piercing: "Piercing",
  power: "Power",
  punch: "Punch",
  snipe: "Snipe",
  ultimate_duplex: "Duplex",
  ultimate_rend: "Rend",
  aqua_affinity: "Aqua Affinity",
  big_brain: "Big Brain",
  transylvanian: "Transylvanian",
  blast_protection: "Blast Protection",
  ferocious_mana: "Ferocious Mana",
  fire_protection: "Fire Protection",
  growth: "Growth",
  hardened_mana: "Hardened Mana",
  hecatomb: "Hecatomb",
  mana_vampire: "Mana Vampire",
  projectile_protection: "Projectile Protection",
  protection: "Protection",
  rejuvenate: "Rejuvenate",
  respiration: "Respiration",
  respite: "Respite",
  strong_mana: "Strong Mana",
  thorns: "Thorns",
  ultimate_bank: "Bank",
  ultimate_habanero_tactics: "Habanero Tactics",
  ultimate_bobbin_time: "Bobbin' Time",
  ultimate_last_stand: "Last Stand",
  ultimate_legion: "Legion",
  ultimate_no_pain_no_gain: "No Pain No Gain",
  ultimate_wisdom: "Wisdom",
  reflection: "Reflection",
  counter_strike: "Counter-Strike",
  true_protection: "True Protection",
  smarty_pants: "Smarty Pants",
  depth_strider: "Depth Strider",
  feather_falling: "Feather Falling",
  frost_walker: "Frost Walker",
  sugar_rush: "Sugar Rush",
  compact: "Compact",
  efficiency: "Efficiency",
  fortune: "Fortune",
  pristine: "Pristine",
  silk_touch: "Silk Touch",
  smelting_touch: "Smelting Touch",
  rainbow: "Rainbow",
  cultivating: "Cultivating",
  dedication: "Dedication",
  delicate: "Delicate",
  harvesting: "Harvesting",
  replenish: "Replenish",
  turbo_cactus: "Turbo-Cacti",
  turbo_cane: "Turbo-Cane",
  turbo_carrot: "Turbo-Carrot",
  turbo_mushrooms: "Turbo-Mushrooms",
  turbo_potato: "Turbo-Potato",
  turbo_warts: "Turbo-Warts",
  turbo_wheat: "Turbo-Wheat",
  sunder: "Sunder",
  turbo_cocoa: "Turbo-Cocoa",
  turbo_melon: "Turbo-Melon",
  turbo_pumpkin: "Turbo-Pumpkin",
  angler: "Angler",
  blessing: "Blessing",
  caster: "Caster",
  charm: "Charm",
  corruption: "Corruption",
  expertise: "Expertise",
  frail: "Frail",
  luck_of_the_sea: "Luck of the Sea",
  lure: "Lure",
  magnet: "Magnet",
  piscary: "Piscary",
  spiked_hook: "Spiked Hook",
  ultimate_flash: "Flash",
  cayenne: "Cayenne",
  green_thumb: "Green Thumb",
  prosperity: "Prosperity",
  quantum: "Quantum",
  ultimate_the_one: "The One",
};

export const colorCodesToClassNames: Record<string, string> = {
  0: "minecraft-black",
  1: "minecraft-dark-blue",
  2: "minecraft-green",
  3: "minecraft-dark-aqua",
  4: "minecraft-dark-red",
  5: "minecraft-dark-purple",
  6: "minecraft-gold",
  7: "minecraft-gray",
  8: "minecraft-dark-gray",
  9: "minecraft-blue",
  a: "minecraft-green",
  b: "minecraft-aqua",
  c: "minecraft-red",
  d: "minecraft-light-purple",
  e: "minecraft-yellow",
  f: "minecraft-white",
  z: "chroma",
  Z: "chroma",
};

export const colorCodesToDisplayNames: Record<string, string> = {
  0: "Black",
  1: "Dark blue",
  2: "Green",
  3: "Dark aqua",
  4: "Dark red",
  5: "Dark purple",
  6: "Gold",
  7: "Gray",
  8: "Dark gray",
  9: "Blue",
  a: "Green",
  b: "Cyan",
  c: "Red",
  d: "Light purple",
  e: "Yellow",
  f: "White",
  z: "SBA chroma",
  Z: "NEU chroma",
};
